(function(g){var window=this;'use strict';var E3=function(a){a.publish("cardstatechange",a.Ok()&&a.kp()?1:0)},F3=function(a,b){var c=g.cb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Job=function(a){var b=g.Rs(a);
a=g.Us(a);return new g.Fs(b.x,b.y,a.width,a.height)},Kob=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.NB(a,b,function(){g.OB(e);c.apply(a,arguments)},d)},I3=function(a){a=g.fb(a);
delete G3[a];g.gd(G3)&&H3&&H3.stop()},Mob=function(){H3||(H3=new g.xv(function(){Lob()},20));
var a=H3;a.isActive()||a.start()},Lob=function(){var a=g.kb();
g.Uc(G3,function(b){Nob(b,a)});
g.gd(G3)||Mob()},J3=function(a,b,c,d){g.Kv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Nob=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Oob(a,a.progress);1==a.progress?(a.j=0,I3(a),a.onFinish(),a.Nr()):a.isPlaying()&&a.AM()},Oob=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Pob=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},K3=function(a,b,c,d,e){J3.call(this,b,c,d,e);
this.element=a},Qob=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
K3.call(this,a,b,c,d,e)},Rob=function(a){return Math.pow(a,3)},Sob=function(a){return 3*a*a-2*a*a*a},Tob=function(a){g.I.call(this);
this.B=a||window;this.j=[]},L3=function(a){return a.baseUrl||null},M3=function(a,b){return g.Ot(g.$r(a,b),function(c){return!!c})},Uob=function(a,b,c){function d(ka){var ia=ka.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var sa=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var U=f(ia.subscriberCountWithUnsubscribeText);var Ia=f(ia.subscriberCountText)}else U=f(ia.subscriberCountText),Ia=f(ia.subscriberCountWithSubscribeText);var x=null;if(ka.signinEndpoint){x=F3(ka,"signinEndpoint","webNavigationEndpointData","url");if(!x){var ba,La;x=null==(La=g.V(null==(ba=ia.signInEndpoint)?void 0:ba.commandMetadata,g.x2))?void 0:
La.url}if(!x)return null}return sa&&(aa||x)?{subscribed:ia.subscribed,subscribeText:sa,subscribeCount:U,unsubscribeText:aa,unsubscribeCount:Ia,enabled:ia.enabled,signinUrl:x,classic:ka.useClassicSubscribeButton}:null}
function e(ka){if(ka){var ia=[],sa=ka.videoId;sa&&ia.push("v="+sa);(sa=ka.playlistId)&&ia.push("list="+sa);(ka=ka.startTimeSeconds)&&ia.push("t="+ka);return"/watch?"+ia.join("&")}}
function f(ka){if(!ka)return null;var ia=ka.simpleText;return ia?ia:ka.runs?g.$r(ka.runs,function(sa){return sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,w=!1,A=null,D=null,F=null,H=null,L=null,M=null;if("VIDEO"===h)g.V(l,g.xF)?m=g.V(l,g.xF).url:(M=g.V(l,g.QS),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.V(l,g.xF)?m=g.V(l,g.xF).url:(M=g.V(l,g.QS),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(w=F3(l,"browseEndpoint","browseId"))v=w,m="/channel/"+v;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((F=F3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=F3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=F3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:null,
ea="";if(b.metadata){var la=f(b.metadata);la&&(ea=la)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ea,callToAction:f(b.callToAction),pX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,WE:p,playlistLength:t,channelId:v,subscribeButton:A,subscribersText:D,isSubscribe:w,targetUrl:m||null,M9:n,sessionData:R?{itct:R}:null,dea:q,tD:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:M3(b.impressionUrls||[],L3),A9:M3(b.hovercardShowUrls||[],L3),clickUrls:M3(l.loggingUrls||[],L3),visualElement:g.CE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:M||null}},Vob=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:M3(a.impressionUrls||[],L3),elements:M3(a.elements||[],function(d,e){return Uob(b,d,e)})};
a.trackingParams&&(c.visualElement=g.CE(a.trackingParams));return c},Wob=function(a){g.tV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.HR(a)||g.JR(a);this.events=new g.bK(this);g.N(this,this.events);this.events.T(this.player,g.jJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.kJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.dc);this.events.T(window,"focus",this.qca);this.load();var b=g.yf("STYLE");(g.nf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Hf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Xob=function(a){return a.player.getVideoData().Hf?"current":a.Z?"new":"current"},N3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Yob=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Vob(f,Xob(a))));O3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Iv;d&&(c.postParams={ad_tracking:d});if(b=g.EWa(b))if(b=g.je(b),b=g.de(b))a.C=g.bB(b,c)},O3=function(a,b,c){c=void 0===c?!0:c;
a.player.mf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Zob(a);c=[];d=new g.iJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.VT(a.player,a.B.element,4),a.D=new g.LF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=$ob(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.VT(a.player,f.element,4);var h=new g.iJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);apb(a,f,e)}else g.IE(new g.dC("buildEndscreenElement null",
e))}a.player.gf(c);a.dc()}},Zob=function(a){var b=g.DE(),c=g.EE();
c&&b&&a.endscreen.visualElement&&g.IA(g.QE)(void 0,c,b,a.endscreen.visualElement)},$ob=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.tD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:P3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:Q3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Ov(b.title||"")},xa:b.title},{I:"div",S:b.WE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.tD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:P3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:Q3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Ov(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.tD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Ov(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P3(b)}]};c=new g.W(c);var d=g.of(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Fv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.cW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.tD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Ov(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:bpb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.tD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Ov(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:P3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Fv(c.element,"ytp-ce-placeholder");return c},P3=function(a){if(a.pX)var b=a.pX.thumbnails;
return bpb(b?b[b.length-1].url:null)},bpb=function(a){return a?{style:"background-image: url("+a+")"}:{}},apb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Fv(b.element,"ytp-ce-force-expand"),R3(a,c.id,!0)):(g.Hv(b.element,"ytp-ce-force-expand"),g.Hv(b.element,"ytp-ce-element-hover"),R3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){cpb(a,b,c)});
b.listen("mouseleave",function(){dpb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Fv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){epb(a,c,m)});
b.listen("keypress",function(m){epb(a,c,m)});
b.listen("focus",function(){cpb(a,b,c)});
b.listen("blur",function(){dpb(a,b,c)});
b.listen("touchstart",function(){cpb(a,b,c)});
var l=g.tf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Hv(b.element,"ytp-ce-element-hover");g.Hv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.tf("ytp-sb-subscribe",b.element));d(g.tf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},epb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Ev(d,"ytp-ce-element");){g.Ev(d,"subscribe-label")&&fpb(a,b);
if(g.Ev(d,"ytp-ce-channel-subscribe"))return;d=g.If(d)}if(!d||g.Ev(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])dpb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.dea)fpb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.je(Q3(a,b.targetUrl)),c=g.de(c),g.mG(c,void 0,b.sessionData);else{var e=g.SR(a.player.U())||a.player.getVideoData().Hf,f=function(){var h=Q3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.NA(h);e&&n&&
(n.v||n.list)?a.player.Qo(n.v,l,n.list,!1,void 0,m||void 0):g.xya(h,l)};
fpb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.$R(a)+b}else return"";return b},cpb=function(a,b,c){g.Ev(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Fv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.xv(function(){g.Fv(b.element,"ytp-ce-element-hover")},200)).start():g.Fv(b.element,"ytp-ce-element-hover"),S3(a,c.A9),R3(a,c.id,!0))},dpb=function(a,b,c){g.Hv(b.element,"ytp-ce-element-hover");
g.Hv(b.element,"ytp-ce-force-expand");R3(a,c.id,!1)},R3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Jv(a.j[e].element,"ytp-ce-element-shadow-show",c)},S3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||N3(a))c&&c();else{b=gpb(a,b);var e=0,f=!1,h=new g.xv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.xD(b[a],d)}},fpb=function(a,b,c){S3(a,b.clickUrls,c);
(a=g.EE())&&b.M9&&g.XE(a,b.visualElement)},gpb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(hpb(b[d],c));return a},hpb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},ipb=function(a){return"string"===typeof a?a:""},T3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jpb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},U3=function(a){return a.value?a.value:null},V3=function(a){if(!a)return null;
var b=g.je(ipb(a.value));b=g.de(b);if(!b)return null;var c=T3(a.target,kpb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new jpb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},lpb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},opb=function(a){if(!a)return null;
var b=T3(a.type,mpb),c=T3(a.trigger,npb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=V3(a?a:null);return b?new lpb(b,c,a):null},ppb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},qpb=function(a,b){return g.Db(a.action,b)},rpb=function(a,b){this.context=a;
this.j=b},spb=function(a){return a.customMessage?W3("div","iv-card-message",a.customMessage):""},X3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},tpb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(W3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},W3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Ov(c);return{I:a,X:b,xa:c}},upb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ED&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ED+");");c.dir=g.Ov(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},Y3=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.ej.click,5)}},vpb=function(a,b){this.merchant=a;
this.price=b},wpb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},xpb=function(a,b){return b?b:wpb(a)?"current":"new"},Z3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Wa=new Map;this.bb=new Map;this.context.J.addEventListener(g.jJ("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.kJ("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)})},$3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.BM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},ypb=function(a){var b;
return(null==(b=g.V(a,g.xF))?0:b.url)?g.V(a,g.xF).url:(a=g.V(a,g.QS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},a4=function(a,b,c){return{OY:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
P1:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
VL:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},zpb=function(a,b,c){Z3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Gb=this.Na=this.Kb=this.C=this.isInitialized=!1;this.cards=[];this.zb=this.Z=this.La=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Ef=this.Ga=null;this.K=0;this.Ea=new g.xv(function(){},c.W.Hl?4E3:3E3);
g.N(this,this.Ea);this.gb=new g.xv(function(){});
g.N(this,this.gb);this.Ca=new rpb(c,function(e,f,h,l,m,n){$3(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Kartlar\u0131 gizle",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.Za=new g.LF(this.Y,330);g.N(this,this.Za);this.Jb=g.tf("iv-drawer-header-text",this.D);this.B=g.tf("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Kb&&b4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.C)&&c4(d)});
this.Sa=new g.bK(this);g.N(this,this.Sa);this.J.addEventListener("videodatachange",this.Kt.bind(this))},Apb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){b4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){c4(a)});
var c=b.headerText;g.Kf(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.CE(b.trackingParams);a.N=g.CE(b.closeTrackingParams);a.Ef=g.CE(b.iconTrackingParams)},Bpb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.fb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.kF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,ej:{},qp:null,Jj:e.trackingParams?g.CE(e.trackingParams):null,Ef:f&&f.trackingParams?g.CE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
ED:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};d4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.kF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:e4(a,c,b,f),sponsored:!1,ej:a4(f,e,f.command),qp:f.trackingParams?g.CE(f.trackingParams):null,Jj:e.trackingParams?g.CE(e.trackingParams):null,Ef:l&&l.trackingParams?g.CE(l.trackingParams):null,imageUrl:f4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.kF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,ED:null,title:f.title?g.kF(f.title):"",customMessage:f.callToAction?g.kF(f.callToAction):"",url:g.V(f.command,g.xF).url?V3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.xF).url}):null,onClickCommand:null};d4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.kF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:e4(a,c,b,e),sponsored:!1,ej:a4(e,f,e.endpoint),qp:e.trackingParams?g.CE(e.trackingParams):null,Jj:f.trackingParams?g.CE(f.trackingParams):null,Ef:l&&l.trackingParams?g.CE(l.trackingParams):null,channelId:g.V(e.endpoint,g.eT).browseId,customMessage:e.customText?g.kF(e.customText):null,profileImageUrl:f4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.kF(e.channelName):"",metaInfo:[e.subscriberCountText?g.kF(e.subscriberCountText):""],url:V3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.eT).canonicalBaseUrl?g.V(e.endpoint,g.eT).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.eT).browseId}),onClickCommand:null};d4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.kF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e4(a,c,b,e),sponsored:!1,ej:a4(e,f,e.action),qp:e.trackingParams?g.CE(e.trackingParams):null,Jj:f.trackingParams?g.CE(f.trackingParams):null,Ef:l&&l.trackingParams?g.CE(l.trackingParams):null,hH:f4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.kF(e.customMessage):null,playlistVideoCount:g.kF(e.playlistVideoCount),title:e.playlistTitle?g.kF(e.playlistTitle):"",metaInfo:[e.channelName?g.kF(e.channelName):
"",e.videoCountText?g.kF(e.videoCountText):""],url:V3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ypb(e.action)}),onClickCommand:null};d4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.kF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:e4(a,c,b,e),sponsored:!1,ej:a4(e,f,e.action),qp:e.trackingParams?g.CE(e.trackingParams):null,Jj:f.trackingParams?g.CE(f.trackingParams):null,Ef:l&&l.trackingParams?g.CE(l.trackingParams):null,hH:f4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.kF(e.lengthString):null,customMessage:e.customMessage?g.kF(e.customMessage):null,title:e.videoTitle?g.kF(e.videoTitle):"",metaInfo:[e.channelName?g.kF(e.channelName):
"",e.viewCountText?g.kF(e.viewCountText):""],isLiveNow:!!e.badge,url:V3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ypb(e.action)}),onClickCommand:null};d4(a,b)}}}}}a.K++},f4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},e4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Dpb=function(a,b){if(b=Cpb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.zf.id),g.Hf(b.WN),g.Hb(a.cards,b),a.kI(),g4(a)},b4=function(a,b,c){if(!a.C){a.Za.show();
a.Va=new g.xv(function(){g.Fv(a.context.J.getRootNode(),g.IY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.EE();d&&a.Ga&&a.N&&g.VE(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.IZ||(f.IZ=!0,Epb(a.context.logger,f.zf.ej.OY,b)),d&&g.VE(d,[f.zf.qp]);E3(a.J);c&&(a.G=new g.xv(function(){a.La=a.Z;a.zb.focus()},330),a.G.start())}},c4=function(a){a.C&&(a.Za.hide(),g.TB(a.Sa),g.Hv(a.context.J.getRootNode(),g.IY.IV_DRAWER_OPEN),a.C=!1,E3(a.J),a.G&&a.G.stop(),a.G=new g.xv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Fpb=function(a){g.Gv(a.Hb(),
[g.IY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.VT(a.J,a.D,5);a.YH();a.Z=g.tf("ytp-cards-button",a.J.getRootNode());a.zb=g.tf("iv-drawer-close-button",a.D);a.isInitialized=!0},Gpb=function(a){a.qa.push(g.LD("iv-teaser-shown",a.p4,a));
a.qa.push(g.LD("iv-teaser-hidden",a.g$,a));a.qa.push(g.LD("iv-teaser-clicked",a.o4,a));a.Gb=!0},Hpb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.V(b.onClickCommand,g.klb))?void 0:c.targetId)?(a.ra=b,!0):!1},Ipb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.bVa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.V(h[0],g.w2a))?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},d4=function(a,b){if(!Hpb(a,b)||Ipb(a,b)){var c=Jpb(a,b);
if(c){var d={zf:b,WN:c.element,IZ:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Gb||Gpb(a),Dpb(a,b.id),c=a.findLastIndex(d),g.Ob(a.cards,c,0,d));else{a.isInitialized||Fpb(a);Dpb(a,b.id);var e=a.findLastIndex(d);g.Ob(a.cards,e,0,d);c.Ja(a.B,e);a.kI()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,g4(a),Kpb(a,d),b4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Lpb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Lpb(a,d)}),g4(a))}}},Jpb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=upb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?U3(b.url)||"":""},V:[X3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[W3("h2",void 0,b.title),d]}]}]};c=new g.W(c);Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:U3(b.url)||"","data-ytid":b.channelId},V:[X3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[spb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},tpb(b)]}]}]};c=new g.W(c);Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:U3(b.url)||""},V:[X3(b.hH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[spb(b),W3("h2","iv-card-primary-link",b.title),tpb(b)]}]}]};
c=new g.W(c);Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=upb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?U3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsorlu",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[W3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.yf("span");g.Kf(d,"Videoyla ilgili oldu\u011funu d\u00fc\u015f\u00fcnd\u00fc\u011f\u00fcm\u00fcz i\u00e7in bu \u00fcr\u00fcn\u00fc g\u00f6r\u00fcyorsunuz. Google, sat\u0131c\u0131 taraf\u0131ndan tazmin edilebilir.");
c.Md(d,"adInfo");Y3(a,g.sf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"CANLI YAYINDA"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:(null==(c=b.url)?void 0:U3(c))||""},V:[X3(b.hH,d),{I:"div",S:"iv-card-content",V:[spb(b),W3("h2","iv-card-primary-link",b.title),tpb(b),f]}]}]};c=new g.W(e);Y3(a,g.sf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Mpb=function(a){if(a.j)return"productListing"===a.j.zf.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.as(a.cards,function(c){return"productListing"===c.zf.type})}return g.as(a.cards,function(c){return"productListing"===c.zf.type})},g4=function(a){g.Jv(a.J.getRootNode(),"ytp-cards-shopping-active",Mpb(a))},Lpb=function(a,b){if(!g.Ev(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.EE(),d=a.j?a.j.zf.Ef:a.Ef;
c&&d&&g.WE(c,[d]);a.j=b;g4(a)}(c=a.isInitialized&&"none"==a.Hb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.zf.teaserDurationMs&&a.J.PB(!0,{teaserText:b.zf.teaserText,durationMs:b.zf.teaserDurationMs,onClickCommand:b.zf.onClickCommand});a.gb.isActive()||((!a.C||!a.Ea.isActive()&&a.Na)&&Kpb(a,b),a.gb.start(910+b.zf.teaserDurationMs))}},Kpb=function(a,b){a.Y.Fb?(b=new J3([0,
a.B.scrollTop],[0,b.WN.offsetTop],600,Sob),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.gF(a.Y,!0),a.B.scrollTop=b.WN.offsetTop,g.gF(a.Y,!1))},h4=function(a){return a.j&&a.j.zf?a.j.zf:a.cards[0]&&a.cards[0].zf?a.cards[0].zf:null},Cpb=function(a,b){return g.Db(a.cards,function(c){return c.zf.id===b})},i4=function(a,b,c){Z3.call(this,a,b);
this.annotation=c;this.isActive=!1},Npb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Opb=function(a,b){var c=void 0===c?0:c;
var d=Job(b).width;g.Ps(b,d);c=new Qob(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Rob);g.N(a,c);a.context.C.listen(c,"begin",function(){g.Vs(b,!0)});
c.play()},Rpb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.cW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Vs(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Is(l,"right",b.image_width+"px");g.Bf(a.Hb(),l);a.C=new g.xv(function(){Ppb(a,h,l)},500);
g.N(a,a.C);a.context.j.listen(a.Hb(),"mouseover",function(){Qpb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Hb(),"mouseout",function(){a.C.start()})}},Qpb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Us(b);a.j||(b.style.width=g.Os(f.width,!0),c.style.width=g.Os(f.width,!0));g.Is(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Is(d,"right","1px");a.D=!0;g.Vs(b,!0);a.G=new g.xv(function(){g.Fv(this.Hb(),"iv-branding-active")},0,a);
a.G.start()}},Ppb=function(a,b,c){g.Hv(a.Hb(),"iv-branding-active");
a.K=new g.xv(function(){g.Vs(b,!1);a.j||(c.style.width=g.Os(0,!0))},250);
a.K.start();a.D=!1},Spb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Tpb=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.xv(function(){d.j.setAttribute("aria-hidden","true");g.Vs(d.C,!1);g.Vs(d.B,!0)},700,this);
g.N(this,this.G)},Wpb=function(a,b,c){c.stopPropagation();
Upb(a);Vpb(a,b);a.j.focus()},Xpb=function(a){a.isCollapsed||a.Z||a.D||(g.Fv(a.Hb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Upb=function(a){a.G.stop();
a.isCollapsed&&(g.Iv(a.Hb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Vs(a.B,!1),g.Vs(a.C,!0))},Vpb=function(a,b){a.D||(a.D=g.Ag(function(){Ypb(this);
Xpb(this)},b,a))},Ypb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},Zpb=function(a){this.J=a},Epb=function(a,b,c){b&&(c?k4(a,b.map(function(d){return g.cv(d,c)})):k4(a,b))},k4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.xD(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},$pb=function(a){g.tV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new Zpb(this.player);this.D=new g.bK(this);this.G=this.N=null;this.events=new g.bK(this);this.Ug=this.Y=this.j=null;this.ra=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.q4,this);this.subscribe("resize",this.MK,this);this.player.U().Na.subscribe("vast_info_card_add",this.P_,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.VT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.Mu()&&this.load();var c=this.createElement({I:"style"});(g.nf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Hf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},aqb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Vs(a,!1);return a},bqb=function(a,b){b=!b.isCued()&&!g.SF(b,1024);
g.gF(a.B,b);g.gF(a.C,b)},cqb=function(a,b,c){a.Z=!0;
a.G=g.bB(b,c)},dqb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.db(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(dqb(a,e))}return c},hqb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.VA(h)&&h.responseXML?h.responseXML:null)&&eqb(a,h)}};
g.lC()&&(d.onFinish=fqb(a,d.onFinish));d.postParams={ic_only:"1"};gqb(d,c);a.Z=!0;g.bB(b.Va,d)}}},gqb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.pI&&(a.postParams.ic_coll=b.pI);b.XN&&(a.postParams.ic_xml=b.XN);b.aM&&(a.postParams.ic_track=b.aM)},iqb=function(a){var b=new g.W({I:"div"});
g.Vs(b.element,!1);var c=new zpb(a.player,b.element,l4(a));g.N(c,b);b.Ja(a.B.element);c.SG();return c},kqb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.qa=!0,jqb(a,b),b.headerText&&a.Ug&&(c=g.kF(b.headerText),a.Ug.setAttribute("title",c))},l4=function(a){if(!a.Y){var b=new Tob(a);
g.N(a,b);var c=new g.oq(a);g.N(a,c);a.Y=new Spb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.tj)}return a.Y},eqb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.EE();if(e){var f=g.DE();f&&g.IA(g.Wwa)(void 0,e,f,[g.CE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=dqb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=T3(f.type,lqb),p=T3(f.style,mqb),q=ipb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=opb;if(null==t)var v=null;else if(g.cb(t)){l=[];for(var w=g.u(t),A=w.next();!A.done;A=w.next()){var D=f(A.value);
D&&l.push(D)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new ppb(m,n,p,v,r):null}else e=null}catch(la){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=aqb(f),L=null;switch(l.type){case "branding":if(f.player.U().Sd)break;f.B.element.appendChild(H);L=new j4(H,l4(f),l);break;case "promotion":g.VT(f.player,H,4),L=new Tpb(H,l4(f),l)}L&&L.SG();if(f=L)g.N(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=iqb(a),g.N(a,a.j));if("card"===e.type){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={OY:f.impression,click:f.click,close:f.close,P1:f.teaser_impression,VL:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,qp:l.card?g.CE(l.card):null,Jj:l.teaser?g.CE(l.teaser):null,Ef:l.icon?g.CE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,
qp:l.card?g.CE(l.card):null,Jj:l.teaser?g.CE(l.teaser):null,Ef:l.icon?g.CE(l.icon):null,hH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d4(H,c);break;case "productListing":e.signin_url&&(L=V3({target:"current",value:e.signin_url}));M=[];for(var R=e.offers||[],ea=0;ea<R.length;ea++)M.push(new vpb(g.bf(R[ea].merchant),
g.bf(R[ea].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,qp:l.card?g.CE(l.card):null,Jj:l.teaser?g.CE(l.teaser):null,Ef:l.icon?g.CE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,ED:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),arb:L,Zqb:e.signin_title?e.signin_title:void 0,Yqb:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};d4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,qp:l.card?g.CE(l.card):
null,Jj:l.teaser?g.CE(l.teaser):null,Ef:l.icon?g.CE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,ED:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};d4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,ej:f,qp:l.card?g.CE(l.card):null,Jj:l.teaser?g.CE(l.teaser):null,Ef:l.icon?g.CE(l.icon):null,hH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:V3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},d4(H,c)}}else Apb(a.j,e);c=!0}}c&&
(E3(a.player),a.MK())},jqb=function(a,b){var c=!1;
a.j||(a.j=iqb(a),g.N(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Bpb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.lT(f)||(c=a.j,d=b.headerText?g.kF(b.headerText):"",g.Kf(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.CE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.CE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ef=b.icon.infoCardIconRenderer.trackingParams?g.CE(b.icon.infoCardIconRenderer.trackingParams):null,a.MK());E3(a.player)}},nqb=function(a,b,c,d,e){if(!a.player.U().Sd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.eT)&&g.V(b.navigationEndpoint,g.eT).browseId&&f.push(new lpb("openUrl","click",new jpb("/channel/"+g.V(b.navigationEndpoint,g.eT).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.fT)){d.channel_id=g.V(b.subscribeButton,g.fT).channelId;var l;b=g.V(b.subscribeButton,g.fT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.kF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.kF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.kF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.kF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.V(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.x2))?void 0:m.url)||"";l={subscribeText:g.kF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.kF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new ppb(c,"branding","branding",f,d);l=aqb(a);a.B.element.appendChild(l);f=new j4(l,l4(a),f);f.SG();g.N(f,f);a.K[c]=f}},fqb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.Ma()||a.ra.push(g.fv.Ni(function(){b.apply(null,g.qa(c))}))}},oqb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.OT.prototype.PB=g.fa(28,function(a,b){var c=g.LV(this.yb());c&&c.PB(a,b)});
var G3={},H3=null;g.nb(J3,g.Kv);g.k=J3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;I3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.DK();this.zn("play");this.isPaused()&&this.zn("resume");this.j=1;var b=g.fb(this);b in G3||(G3[b]=this);Mob();Nob(this,a);return!0};
g.k.stop=function(a){I3(this);this.j=0;a&&(this.progress=1);Oob(this,this.progress);this.onStop();this.Nr()};
g.k.pause=function(){this.isPlaying()&&(I3(this),this.j=-1,this.zn("pause"))};
g.k.va=function(){0==this.j||this.stop(!1);this.zn("destroy");J3.Nf.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.AM=function(){this.zn("animate")};
g.k.zn=function(a){this.dispatchEvent(new Pob(a,this))};
g.nb(Pob,g.Ab);g.nb(K3,J3);K3.prototype.C=function(){};
K3.prototype.AM=function(){this.C();K3.Nf.AM.call(this)};
K3.prototype.Nr=function(){this.C();K3.Nf.Nr.call(this)};
K3.prototype.DK=function(){this.C();K3.Nf.DK.call(this)};
g.nb(Qob,K3);Qob.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(Tob,g.I);g.k=Tob.prototype;g.k.listen=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=g.NB(a,b,c);this.j.push(a);return a};
g.k.oF=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=Kob(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.OB(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.OB(this.j);this.j.length=0};
g.k.va=function(){this.removeAll();g.I.prototype.va.call(this)};g.y(Wob,g.tV);g.k=Wob.prototype;g.k.load=function(){g.tV.prototype.load.call(this);if(!N3(this)){var a=g.FWa(this.player.getVideoData());a?(a=Vob(a,Xob(this)),O3(this,a,!1)):Yob(this)}};
g.k.unload=function(){O3(this,null);this.C&&(this.C.abort(),this.C=null);g.tV.prototype.unload.call(this)};
g.k.Qh=function(a,b){return N3(this)?"loadCustomEndscreenRenderer"===a?(a=Vob(b,"new"),O3(this,a),!0):null:null};
g.k.getOptions=function(){return N3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.dc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<pqb.length;f++){var h=Math.abs(b.width-pqb[f]);if(-1===e||d>=h)e=f,d=h}d=qqb[e];this.B&&g.Is(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ts(e.element,m,f);g.Ps(e.element,n,p);g.Iv(e.element,rqb);256<m||256<f?g.Fv(e.element,"ytp-ce-large-round"):96<m||96<f?g.Fv(e.element,"ytp-ce-medium-round"):g.Fv(e.element,"ytp-ce-small-round");g.Iv(e.element,sqb);m=h.left+h.width/2;h=h.top+l/2;g.Fv(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Iv(e.element,qqb);g.Fv(e.element,d);(e=g.of(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Is(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())S3(this,this.endscreen.impressionUrls),(a=g.EE())&&this.endscreen.visualElement&&g.UE(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Fv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Fv(b,"ytp-ce-shown");S3(this,c.impressionUrls);(b=g.EE())&&g.UE(b,c.visualElement);this.player.U().N&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Hv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Hv(b,"ytp-ce-shown");this.player.U().N&&this.player.jb("endscreenelementhidden",a)}};
g.k.qca=function(a){var b=this;a.target===window&&(new g.xv(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Iv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var pqb=[346,426,470,506,570,640,853,1280,1920],qqb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),sqb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],rqb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var kpb={fwa:"current",pXa:"new"};var mpb={CLOSE:"close",g0a:"openUrl",SUBSCRIBE:"subscribe"},npb={qua:"click",CLOSE:"close",iIa:"hidden",m6a:"rollOut",n6a:"rollOver",e8a:"shown"};ppb.prototype.Le=function(){var a=qpb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var mqb={Foa:"anchored",q3:"branding",CHANNEL:"channel",Uva:"cta",lIa:"highlightText",pMa:"label",PLAYLIST:"playlist",POPUP:"popup",iab:"speech",SUBSCRIBE:"subscribe",Xdb:"title",VIDEO:"video",Clb:"website"},lqb={q3:"branding",Qra:"card",dya:"drawer",kIa:"highlight",GSa:"marker",w4a:"promotion",TEXT:"text",knb:"widget"};g.y(Z3,g.I);g.k=Z3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.iJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.bb.set(a,e);this.context.J.gf([a])};
g.k.SG=function(){this.context.B.subscribe("resize",this.kI,this)};
g.k.Hb=function(){return this.element};
g.k.BM=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Hf(this.Hb())};
g.k.kI=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=U3(a);if(f){var h=xpb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Hf||!1,n=g.NA(f||"");m&&n&&(n.v||n.list)?e.context.J.Qo(n.v,b,n.list,!1):g.mG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);k4(this.context.logger,c,l,d);wpb(f)||(c=g.EE(),d=b.itct,c&&d&&g.XE(c,g.CE(d)))}};
g.k.va=function(){this.Wa.clear();this.bb.clear();g.I.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.y(zpb,Z3);g.k=zpb.prototype;g.k.Kt=function(){this.ra&&d4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Us(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.kI=function(){var a=this.isAvailable();g.Vs(this.Hb(),a);g.Jv(this.context.J.getRootNode(),g.IY.IV_DRAWER_ENABLED,a);E3(this.J)};
g.k.destroy=function(){this.J.PB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.MD(this.qa);g.TB(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();Z3.prototype.destroy.call(this)};
g.k.YH=function(){var a=this,b=g.tf("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.k7,this);this.context.j.listen(this.B,"touchend",function(){a.Ea.start()});
this.context.j.listen(this.B,"scroll",this.H7,this);this.context.B.subscribe("onHideControls",function(){a.Na=!0});
this.context.B.subscribe("onShowControls",function(){a.Na=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Ev(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.LD("iv-button-shown",this.f$,this));this.qa.push(g.LD("iv-button-hidden",this.e$,this));Gpb(this)};
g.k.findLastIndex=function(a){if(0===this.cards.length)return 0;var b=g.Eb(this.cards,function(c){return a.zf.startMs>c.zf.startMs||a.zf.startMs===c.zf.startMs&&a.zf.timestamp>=c.zf.timestamp?!0:!1});
return-1===b?0:b+1};
g.k.k7=function(){if(this.C){k4(this.context.logger,h4(this).ej.close);var a=g.EE();a&&this.N&&g.XE(a,this.N);c4(this)}};
g.k.H7=function(){g.Jv(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.f$=function(){var a=g.EE(),b=h4(this);b=b?b.Ef:this.Ef;a&&b&&g.VE(a,[b])};
g.k.e$=function(){var a=g.EE(),b=h4(this);b=b?b.Ef:this.Ef;a&&b&&g.WE(a,[b])};
g.k.p4=function(){var a=h4(this);k4(this.context.logger,a.ej.P1);var b=g.EE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Jj&&c.push(a.Jj);a.Ef&&c.push(a.Ef);0<c.length&&g.VE(b,c)}else g.VE(b,[a.Jj,a.Ef])};
g.k.g$=function(){var a=g.EE(),b=h4(this);a&&b&&g.WE(a,[b.Jj])};
g.k.o4=function(a){var b=h4(this),c=g.EE();this.j?a?(a=this.context.logger,k4(a,b.ej.VL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Jj&&g.XE(c,b.Jj)):(a=this.context.logger,k4(a,b.ej.VL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ef&&g.XE(c,b.Ef)):(a=this.context.logger,k4(a,b.ej.VL),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ef&&g.XE(c,this.Ef))};g.y(i4,Z3);i4.prototype.SG=function(){Z3.prototype.SG.call(this);Npb(this)};
i4.prototype.show=function(){Z3.prototype.show.call(this);var a=g.EE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.VE(a,[g.CE(b.itct)])};
i4.prototype.hide=function(){Z3.prototype.hide.call(this);var a=g.EE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.WE(a,[g.CE(b.itct)])};g.y(j4,i4);
j4.prototype.Nx=function(){g.Fv(this.Hb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Kanal filigran\u0131",src:a.image_url,width:a.image_width,height:a.image_height}});g.Vs(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Hb().appendChild(b);var c=this.annotation.Le();c&&$3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Rpb(this,
a)};
j4.prototype.show=function(){if(!this.isActive&&(i4.prototype.show.call(this),this.N||(this.Nx(),this.N=!0),g.Vs(this.Hb(),!0),this.isActive=!0,this.B)){try{Opb(this,this.B)}catch(a){}g.Fv(this.context.J.getRootNode(),"ytp-branding-shown")}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.Vs(this.Hb(),!1),this.isActive=!1,g.Hv(this.context.J.getRootNode(),"ytp-branding-shown"))};
j4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);i4.prototype.destroy.call(this)};g.y(Tpb,i4);g.k=Tpb.prototype;
g.k.Nx=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Hb().setAttribute("aria-hidden","true");this.Hb().setAttribute("aria-label","Tan\u0131t\u0131m");this.Hb().tabIndex=0;var e=this.annotation.Le(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&$3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Me(f,U3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&$3(this,
this.Hb(),e,this.annotation.id,b.session_data,void 0,c)}g.Fv(this.j,"iv-click-target");e&&$3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"CANLI YAYINDA"})),g.Fv(this.j,"iv-click-target"),e&&$3(this,this.j,e,this.annotation.id,b.session_data,
void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Geni\u015flet";this.context.j.listen(this.B,"click",function(q){Wpb(a,5E3,q)});
c.appendChild(this.B);g.Vs(this.B,!1);this.context.j.listen(this.Hb(),"mouseover",this.b9,this);this.context.j.listen(this.Hb(),"mouseout",this.a9,this);this.context.j.listen(this.Hb(),"touchend",function(q){Wpb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Kapat";this.context.j.listen(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.W8:this.V8,this);c.appendChild(this.C);g.Gv(this.Hb(),d);h&&(g.Bf(this.Hb(),h),n&&h.appendChild(n));g.Bf(this.Hb(),this.N);g.Bf(this.Hb(),c)};
g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.Y||(this.Nx(),this.Y=!0),g.Vs(this.Hb(),!0),g.Ag(function(){g.Hv(this.Hb(),"iv-promo-inactive")},100,this),this.Hb().removeAttribute("aria-hidden"),this.isActive=!0,Ypb(this),Upb(this),Vpb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Fv(this.Hb(),"iv-promo-inactive"),this.isActive=!1,this.Hb().setAttribute("aria-hidden","true"))};
g.k.BM=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.BM.call(this,a,b,c,d,e,f)};
g.k.b9=function(a){this.Z=!0;Wpb(this,500,a)};
g.k.a9=function(){this.Z=!1;Xpb(this)};
g.k.V8=function(a){a.stopPropagation();this.hide()};
g.k.W8=function(a){a.stopPropagation();Ypb(this);this.isCollapsed=!0;g.Fv(this.Hb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();i4.prototype.destroy.call(this)};g.y($pb,g.tV);g.k=$pb.prototype;g.k.Qh=function(a,b){if(!oqb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.c2(b))&&eqb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Dpb(this.j,b),E3(this.player)),!0}return null};
g.k.getOptions=function(){return oqb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Mu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.wT(b)||g.HT(this.player.app)?!1:1===c&&!b.sX||a.Na.get(b.videoId)||g.mT(b)||g.GWa(b)?!0:!1};
g.k.MK=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Ts(this.C.element,a.width,a.height);g.Ps(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Hn();a=this.j;b=b.width;g.Jv(a.D,"iv-drawer-small",426>=b);g.Jv(a.D,"iv-drawer-big",1280<=b)}};
g.k.q4=function(a){bqb(this,a.state);g.SF(a.state,2)&&(this.Ok()&&this.kp()&&2!==this.player.getPresentingPlayerType()&&this.QB(!1),this.PB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.VA(h)&&h.responseXML?h.responseXML:null)&&(eqb(b,h),g.Fv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.tV.prototype.load.call(this);bqb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.lC()&&(a=fqb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&gqb(e,f);f=f&&(f.XN||f.pI);if(!c.hv||f)c.Va?cqb(this,c.Va,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.lT(h))&&!b.qa&&kqb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.VT(this.player,this.C.element,4);this.MK();(f=g.mT(c))&&jqb(this,f);(f=g.GWa(c))&&f.featuredChannel&&nqb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Ug=g.tf("ytp-cards-button",this.player.getRootNode());g.lT(c)&&kqb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&cqb(this,b.Va,a)};
g.k.unload=function(){this.player.mf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,E3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.tV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.P_=function(a){a===this.player.getVideoData().videoId&&(this.loaded?hqb(this):this.load())};
g.k.Ok=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.qa};
g.k.kp=function(){return!!this.j&&this.j.C};
g.k.QB=function(a,b,c){b=void 0===b?!1:b;this.Ok();this.j&&(a?c?b4(this.j,c,b):b4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):c4(this.j))};
g.k.PB=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.P_,this);g.Hv(this.player.getRootNode(),g.IY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.fv,c=0,d=a.length;c<d;c++)b.Pj(a[c]);this.ra.length=0;g.tV.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.sV("annotations_module",$pb);g.sV("creatorendscreen",Wob);})(_yt_player);
