(function(g){var window=this;'use strict';var cvb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.Ajb)("0",Math.max(0,b-c))+a},dvb=function(){return{I:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},evb=function(){return{I:"svg",
X:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",X:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},gvb=function(a){"number"===typeof a?(this.date=fvb(a,0,1),y6(this,1)):g.db(a)?(this.date=fvb(a.getFullYear(),a.getMonth(),a.getDate()),y6(this,a.getDate())):(this.date=new Date(g.kb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),y6(this,a))},fvb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},y6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},z6=function(a,b){g.$T.call(this,a,{I:"div",
S:"ytp-reminder-menu",X:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Fa("ytp-reminder-menu-items");this.hide()},hvb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},A6=function(a){g.W.call(this,{I:"div",
V:[{I:"button",Ka:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",xa:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",xa:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Fa("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.G);this.hide()},jvb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.V(c,ivb)?a.upcomingEventReminderButtonRenderer=g.V(c,ivb):c&&g.V(c,ivb)||(a.upcomingEventReminderButtonRenderer=null);B6(a)},B6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.kF(b.toggledText):"";a.update({text:c,icon:kvb(b.toggledIcon)})}else c=b.defaultText?g.kF(b.defaultText):"",a.update({text:c,icon:kvb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=lvb(a))?(c=b.text?g.kF(b.text):"",a.update({text:c,icon:kvb(b.icon)}),a.show()):a.hide():a.hide()},nvb=function(a,b,c){a.D||(a.D=new g.FD(a.J.U().Gk));
var d={context:g.$sa(a.D.config_||g.fD())};g.EE()&&(d.context.clientScreenNonce=g.EE());d.params=c;g.GD(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){mvb(a)},
onTimeout:function(){mvb(a)}})},mvb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,B6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,B6(a))},kvb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return dvb();case "NOTIFICATIONS_NONE":return evb();case "NOTIFICATIONS_ACTIVE":return g.xxa();default:return null}},lvb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.u(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.V(c.value,ovb))&&c.state===b&&c.button&&g.V(c.button,g.rM))return g.V(c.button,g.rM);return null},pvb=function(a){g.W.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",X:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",X:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",X:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",X:{"aria-label":"{{label}}"},xa:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",xa:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",Ka:["ytp-offline-slate-close-button","ytp-button"],V:[g.nF()]},{I:"button",Ka:["ytp-offline-slate-open-button","ytp-button"],V:[g.mF()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Fa("ytp-offline-slate-background");
this.C=this.Fa("ytp-offline-slate-bar");this.G=new g.xv(function(){g.Fv(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.xv(function(){g.Fv(b.element,"ytp-offline-slate-collapsed")},15E3);
g.N(this,this.D);g.N(this,this.G);this.countdownTimer=new g.xv(this.B2,1E3,this);this.T(a,"presentingplayerstatechange",this.F2);this.T(a,"livestatedata",this.Ta);a=this.Fa("ytp-offline-slate-close-button");this.T(a,"click",function(){g.Fv(b.element,"ytp-offline-slate-collapsed")});
a=this.Fa("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Hv(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ta(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Pl;var c=8===this.api.getPresentingPlayerType();g.Jv(this.element,"ytp-offline-slate-premiere-trailer",a);g.Jv(this.element,"ytp-offline-slate-hide-background",c)},qvb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.kF(b.subtitleText):"";
c=c?c:null!=b.mainText?g.kF(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.Jv(a.element,"ytp-offline-slate-single-text-line",!d);g.Jv(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},C6=function(a,b){var c=(0,g.DC)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},wvb=function(a){g.tV.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.xv(function(){rvb(b)},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.Nm(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.qa=new g.FD(void 0);this.attestationResponse=Promise.resolve(void 0);this.Y=Promise.resolve(void 0);this.utcOffsetMinutes=-(new gvb).getTimezoneOffset();this.C=new g.bK(this);g.N(this,this.B);g.N(this,this.C);svb(this);tvb(this);this.C.T(a,"heartbeatparams",this.JF);this.C.T(a,"presentingplayerstatechange",this.F4);this.C.T(a,"videoplayerreset",this.G4);this.C.T(a,g.jJ("heartbeat"),
this.onCueRangeEnter);this.D&&this.j&&uvb(this,void 0,this.j);var c=new g.iJ(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.iJ(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.gf([c,d]);vvb(this)},vvb=function(a){var b=a.getVideoData();
!b.L("use_rta_only_for_player")&&b.Jl&&(b=b.botguardData)&&g.KOa(b,a.player.U())},xvb=function(a){var b,c;
return g.G(function(d){if(1==d.j)return g.z(d,g.bAa(),2);if(!d.B)return 3<=a.sequenceNumber?d.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):d.return(void 0);b=a.getVideoData();c={};return d.return(g.aAa((c.cpn=b.clientPlaybackNonce,c.encryptedVideoId=b.videoId||"",c)))})},svb=function(a){var b=a.getVideoData();
if(b.Jl)if(b.L("use_rta_for_player_hb"))a.attestationResponse=xvb(a);else if(b=new g.IOa(b),g.WO.isInitialized()||3<=a.sequenceNumber){var c=Promise,d=c.resolve,e=null;if(b.videoData.Mq){var f=g.JOa(b);if(f){e={};var h={};f=f.split("&");f=g.u(f);for(var l=f.next();!l.done;l=f.next())l=l.value.split("="),2===l.length&&(h[l[0]]=l[1]);h.r1a&&(e.webResponse=h.r1a);h.r1c&&(e.error=yvb[Number(h.r1c)]);e.challenge=b.videoData.Mq}}a.attestationResponse=d.call(c,e||void 0)}},zvb=function(a){var b=a.getVideoData();
if(!g.aT(a.getVideoData())||b.W2)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_widevine");b=g.bR(b.K)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},Avb=function(a){if(zvb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.aT(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Fl&&!b.iD?!1:!!b.heartbeatToken},D6=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(Avb(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().o1||6E4}else b=1E3;a.B.start(b)}}},Evb=function(a,b,c){b.Zm&&(c=g.to(c,{internalipoverride:b.Zm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Jb&&(d.kpt=b.Jb);c=g.to(c,d);g.bB(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&E6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=Bvb(e);if(f){a.player.jb("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(Cvb))?"0"===h[1]?0:1:-1;Dvb(a,void 0,f,e,h)}},
onError:function(e){E6(a)&&F6(a,!0,"net-"+e.status)},
onTimeout:function(){E6(a)&&F6(a,!0,"timeout")},
withCredentials:!0})},rvb=function(a){var b,c;
g.G(function(d){b=a.player.U();c=a.getVideoData();if(!E6(a))return d.return();if(zvb(a))return Fvb(a,b,c),d.Ia(0);svb(a);return g.z(d,Gvb(a,b,c),0)})},Fvb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.to(a.heartbeatParams.url,{request_id:g.uua()});c.Ca&&(e=g.to(e,{vvt:c.Ca}),c.mdxEnvironment&&(e=g.to(e,{mdx_environment:c.mdxEnvironment})));g.aS(b,c.oauthToken).then(function(f){f&&(e=g.to(e,{access_token:f}));Evb(a,c,e)})}},E6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.SF(a.player.getPlayerStateObject(a.getPlayerType()),4)?!1:Avb(a)||b.isLivePlayback?!0:(G6(a),!1)},Gvb=function(a,b,c){var d,e,f,h,l,m,n,p,q,r,t,v,w,A,D,F,H,L,M,R;
return g.G(function(ea){if(1==ea.j)return d="player/heartbeat",f={videoId:c.videoId,sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(e=a.ra)?e:c.heartbeatServerData},a.Y=a.attestationResponse,c.Jl?g.z(ea,a.Y,3):ea.Ia(2);2!=ea.j&&(f.attestationResponse=ea.B);h=g.yT(c);m=null!=(l=h.client)?l:{};m.utcOffsetMinutes=a.utcOffsetMinutes;f.context=h;f.cpn=c.clientPlaybackNonce;if(n="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=n;p={heartbeatChecks:[]};
if(q=c.getPlayerResponse())c.heartbeatToken&&(f.heartbeatToken=c.heartbeatToken),(r=q.playabilityStatus)&&(t=r.liveStreamability)&&t.liveStreamabilityRenderer&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.MI(b)&&(p.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),v=Hvb(a),w={},null!==v&&(w.clientPlayerPositionUtcMillis=v),D=null==(A=a.player.yb())?void 0:g.JV(A),H=(null==(F=D)?void 0:F.freePreviewWatchedDuration)||
0,0<H&&(w.freePreviewWatchedDuration={seconds:""+H}),p.unpluggedParams=w);f.heartbeatRequestParams=p;c.isLivePlayback?(L=Hvb(a),null!==L&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={utcTimeMillis:L})):b.L("enable_heartbeat_vod_playback_position")&&(M=Ivb(a),null!==M&&(f.playbackState||(f.playbackState={}),f.playbackState.playbackPosition={streamTimeMillis:M}));a.player.publish("heartbeatRequest",f);R={timeout:3E4,onSuccess:function(la){if(!a.B.isActive()&&E6(a)){var ka=
a.getVideoData(),ia=ka.Jl&&null==a.Y,sa;ka.Jl=!(null==(sa=la.heartbeatAttestationConfig)||!sa.requiresAttestation)||ia;ia=la.playabilityStatus;sa=JSON.stringify(ia)||"{}";la.authenticationMismatch&&a.player.ma("authshear",{});var aa=-1;var U=la.playabilityStatus;U&&(a.player.jb("onHeartbeat",U),"OK"===U.status?aa=la.stopHeartbeat?2:0:"UNPLAYABLE"===U.status?aa=1:"LIVE_STREAM_OFFLINE"===U.status&&(aa=0));a.sequenceNumber&&-1===aa||a.K.reset();a.sequenceNumber++;la.heartbeatServerData&&(a.ra=la.heartbeatServerData);
ka.kD=la;(U=la.playerCueRangeSet)&&g.MVa(ka,U);la.playerCueRanges&&0<la.playerCueRanges.length&&(ka.cueRanges=la.playerCueRanges);var Ia,x;(null==(Ia=la.progressBarConfig)?0:Ia.progressBarStartPosition)&&(null==(x=la.progressBarConfig)?0:x.progressBarEndPosition)&&(ka.progressBarStartPosition=la.progressBarConfig.progressBarStartPosition,ka.progressBarEndPosition=la.progressBarConfig.progressBarEndPosition);ka.compositeLiveIngestionOffsetToken=la.compositeLiveIngestionOffsetToken;la.compositeLiveStatusToken!==
ka.compositeLiveStatusToken&&(ka.compositeLiveStatusToken=la.compositeLiveStatusToken);ka.publish("dataupdated");Dvb(a,la,ia,sa,aa)}},
onError:function(la){E6(a)&&F6(a,!0,"net-"+la.status)},
onTimeout:function(){E6(a)&&F6(a,!0,"timeout")}};
g.aS(b,g.rT(c)).then(function(la){la&&(R.tW="Bearer "+la);g.GD(a.qa,d,f,R)});
g.Aa(ea)})},Dvb=function(a,b,c,d,e){-1===e?(c="decode "+g.Ig(d,3),F6(a,!1,c)):2===e?(G6(a),a.G=!0):(a.Z=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.Do(!0),e="pe."+(null==c?void 0:c.errorCode)+";ps."+(null==c?void 0:c.status),a.player.Zf("heartbeat.stop",2,a.qf(d),e),g.pC("heartbeatActionPlayerHalted",Jvb(c)),(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.V(b,g.QS))&&Kvb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):(a.G=
!0,d=0,a.D&&c&&(d=uvb(a,b,c),a.player.publish("livestatedata",c)),d?D6(a,d):D6(a)))},uvb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=Lvb(a,b,d);var f=a.getVideoData(),h=a.player.getPlayerStateObject(a.getPlayerType()),l=h.isPlaying()&&!g.gT(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().zc()){var m,n=(null==(m=a.player.Se())?void 0:m.kc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.ma("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.V(d.streamTransitionEndpoint,g.QS);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&Kvb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!g.dT(f)||l){var p={video_id:f.videoId};f.rD&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.getWatchNextResponse());p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;
p.force_gvi=f.Ym;p.Dm=f.Dm;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Sm);f.Ca&&(p.vvt=f.Ca);d=void 0;g.dT(f)?l&&(d=new C6("broadcastIdChanged",m+","+e),a.gK("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new C6("formatsReceived",""+e)),a.gK("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.zg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Fb&&a.api.VB()):h.isBuffering()&&(f=(null==(p=a.player.Se())?void 0:p.kc())||{},a.player.ma("hbse",f,!0),a.player.VB(),a.player.jb("onLiveMediaEnded",c)));return b},Lvb=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?c:0},F6=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.q2||b&&!g.aT(a.getVideoData())&&!Avb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.retries)?h=a.heartbeatParams.retries:h=f.Q1||5;f=a.Z>=h}f?(g.pC("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:Jvb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Zf(e,1,"Video oynat\u0131m\u0131 kesildi. L\u00fctfen tekrar deneyin.",c):a.player.Zf(e,
1,"Maalesef bu videonun lisanslanmas\u0131nda bir hata olu\u015ftu.",c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.ls(e,{msg:c}),D6(a,a.K.getValue()),g.Om(a.K))}},Jvb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},G6=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},tvb=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.yTa(c.G)){a.D=!0;a.N=!0;if(!g.OI(c)||g.MI(c))a.offlineSlate=new pvb(a.player),g.N(a,a.offlineSlate),g.VT(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=Lvb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?D6(a,d):D6(a,7500):D6(a,1E3))}else a.player.Zf("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Fb(b.Ga,"heartbeat")&&a.player.zg("heartbeat",a.getPlayerType())},Kvb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.Qo(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.rT(a.getVideoData())),a.gK("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},Hvb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},Ivb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},Bvb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},Mvb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
Mvb={ERAS:["M\u00d6","MS"],ERANAMES:["Milattan \u00d6nce","Milattan Sonra"],NARROWMONTHS:"O\u015eMNMHTAEEKA".split(""),STANDALONENARROWMONTHS:"O\u015eMNMHTAEEKA".split(""),MONTHS:"Ocak \u015eubat Mart Nisan May\u0131s Haziran Temmuz A\u011fustos Eyl\u00fcl Ekim Kas\u0131m Aral\u0131k".split(" "),STANDALONEMONTHS:"Ocak \u015eubat Mart Nisan May\u0131s Haziran Temmuz A\u011fustos Eyl\u00fcl Ekim Kas\u0131m Aral\u0131k".split(" "),SHORTMONTHS:"Oca \u015eub Mar Nis May Haz Tem A\u011fu Eyl Eki Kas Ara".split(" "),
STANDALONESHORTMONTHS:"Oca \u015eub Mar Nis May Haz Tem A\u011fu Eyl Eki Kas Ara".split(" "),WEEKDAYS:"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),STANDALONEWEEKDAYS:"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),SHORTWEEKDAYS:"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),STANDALONESHORTWEEKDAYS:"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),NARROWWEEKDAYS:"PPS\u00c7PCC".split(""),STANDALONENARROWWEEKDAYS:"PPS\u00c7PCC".split(""),
SHORTQUARTERS:["\u00c71","\u00c72","\u00c73","\u00c74"],QUARTERS:["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],AMPMS:["\u00d6\u00d6","\u00d6S"],DATEFORMATS:["d MMMM y EEEE","d MMMM y","d MMM y","d.MM.y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:6};
var yvb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=gvb.prototype;g.k.EX=Mvb.FIRSTDAYOFWEEK;g.k.FX=Mvb.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new gvb(this.date);a.EX=this.EX;a.FX=this.FX;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),y6(this,a.getDate()))};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+cvb(Math.abs(a),b?6:4),cvb(this.getMonth()+1,2),cvb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var Nvb=new g.Zw("addUpcomingEventReminderEndpoint");var Ovb=new g.Zw("removeUpcomingEventReminderEndpoint");var Pvb=new g.Zw("updateUpcomingEventReminderButtonStateCommand");var ivb=new g.Zw("upcomingEventReminderButtonRenderer"),ovb=new g.Zw("upcomingEventReminderButtonStateRenderer");g.y(z6,g.$T);
z6.prototype.updateMenuItems=function(){var a=this,b=hvb(this),c=0;c=0;for(var d={};c<b.length;d={RY:void 0},c++){var e=this.j[c];e||(e=new g.W({I:"div",S:"ytp-reminder-menu-item",X:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",xa:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",xa:"{{text}}"}]}),d.RY=c,e.listen("click",function(h){return function(){var l=h.RY;a.Nb();l=hvb(a)[l];a.publish("reminderMenuItemClicked",l.serviceEndpoint||l.command)}}(d)),e.Ja(this.items),
this.j[c]=e);
var f=b[c];d=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":d=dvb();break;case "NOTIFICATIONS_NONE":d=evb();break;case "NOTIFICATIONS_ACTIVE":d=g.xxa()}f=f.text?g.kF(f.text):"";e.update({icon:d,text:f})}for(;c<this.j.length;)this.j.pop().dispose();0===c?this.Nb():this.od(this.buttonElement)};
z6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.$T.prototype.hide.call(this)};
z6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.$T.prototype.show.call(this)};
z6.prototype.va=function(){g.wb(this.j);g.$T.prototype.va.call(this)};g.y(A6,g.W);
A6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;B6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Fb)this.j.Nb();else{var b=lvb(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.V(null==b?void 0:b.command,g.WF))?void 0:a.commands)||[];a:{a=g.u(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.V(c.value,
g.llb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new z6(this.J,this.buttonElement),this.j.Ja(this.element),g.N(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;b.updateMenuItems()}};
A6.prototype.C=function(a){var b=g.V(a,Nvb),c=g.V(a,Ovb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(nvb(this,e,d.params),a=g.u(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.V(b,Pvb)){this.B=g.V(b,Pvb).state;B6(this);break}}};g.y(pvb,g.W);g.k=pvb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Ta=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.B2():qvb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new A6(this.api),this.j.Ja(this.Fa("ytp-offline-slate-buttons")),g.N(this,this.j)),jvb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&jvb(this.j,null,null);this.B=a}else this.B=null;this.F2()};
g.k.F2=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.getPlayerStateObject(),d=this.getVideoData();b=d.isLivePlayback&&(c.isBuffering()||g.SF(c,2)||g.SF(c,64));var e=2===d.autonavState&&g.SF(c,2);c=c.isPlaying()&&!g.gT(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Fb?(null==a?0:g.UF(a,2))&&!this.getVideoData().Pl&&(g.Hv(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.Hv(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),
this.D.start(),this.api.publish("offlineslatestatechange"),this.K&&this.api.VB()):this.Fb&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.k.B2=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.kb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(qvb(this,e),this.countdownTimer.stop()):(qvb(this,e,g.bG(b-a)),g.yv(this.countdownTimer)))};
g.k.va=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.va.call(this)};C6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
C6.prototype.isExpired=function(){return 6E4<(0,g.DC)()-this.C};
C6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.y(wvb,g.tV);g.k=wvb.prototype;g.k.va=function(){G6(this);this.player.mf("heartbeat");g.tV.prototype.va.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;D6(this,2E3)};
g.k.JF=function(a){this.heartbeatParams=a;D6(this,2E3)};
g.k.F4=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.SF(a.state,2)||g.SF(a.state,64)?(G6(this),this.D&&(this.N=!0,D6(this,1E3))):(g.SF(a.state,1)||g.SF(a.state,8))&&D6(this,2E3))};
g.k.G4=function(){3!==this.player.getPresentingPlayerType()&&D6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Mm=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.gK=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.pC("heartbeatActionPlayerTransitioned",a)};
g.k.qf=function(a){var b="LICENSE",c=Bvb(a);if(c)return c.reason||g.SV[b]||"";(a=a.match(Cvb))&&(a=Number(a[1]))&&(b=g.EDa(a));return g.SV[b]||""};
g.k.XE=function(){return!!this.offlineSlate&&this.offlineSlate.Fb};
var Cvb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.sV("heartbeat",wvb);})(_yt_player);
